### ISSUE TITLE
Perl not working

### ISSUE THREAD

**Issue by chillywings** [AdamSpannbauer/r_regex_tester_app#12]
Hi- first of all, very useful app! The only issue that I've found is that it doesn't work when I try using look ahead/behind arguments. I can confirm that my arguments are correct by testing in R and I tried unchecking and rechecking the Perl box. I tested the "Ignore Case" option as well and that seems to work, so I believe only the Perl option is broken. 

Also, a minor issue- inserting any double quotes (") into the test string breaks the app as well. Presumably because the entire string is being quoted with double quotes. Adding a backslash fixes it and I think that behavior is fine as R generally operates that way as well. However, it would be nice if you could output a relevant error to the user to inform them that they need to escape double quotes.

**Comment by AdamSpannbauer** [comment]
RE Perl:
Could you please provide the input you used that broke the app? i.e. the regex and input text?

RE quote issue:
I'll look into it, but I want to be up front.  I haven't really worked on this project in a while due to lack of interest, and to be honest if the fix for this is a lot of effort I likely won't fix it.

**Comment by chillywings** [comment]
As far as I can tell any look ahead/behind arguments will break it. So for example with the default test string "(?<=th)(is)" doesn't capture anything. However, in R this works:
> str_extract("This is a test string for testing regex.", regex("(?<=th)(is)", ignore_case = T))
[1] "is"
> str_locate("This is a test string for testing regex.", regex("(?<=th)(is)", ignore_case = T))
     start end
[1,]     3   4

As for the quotes, I would imagine you could do a simple test on the test string to determine if it's a contiguous string and return an error message if not. However, I did just play with it a little more and checking the auto-escape option does fix the issue.

**Comment by AdamSpannbauer** [comment]
Thanks for the example input! I'm planning to have an open-source day tomorrow and go through all the issues on my projects.  So I've got this one on the list.

I forgot to mention this originally, but thank you very much for reporting the issue.  And thanks for using the app, glad to see it being used and helping someone out.

**Comment by AdamSpannbauer** [comment]
* [ ] Look ahead/behind issue
   * I was naively trying to escape html being input into the regex text input.  Taking out this escaping fixes the issue.  The downside is that now if you try to match an HTML tag using `fixed=TRUE` the results won't render correctly.  I think look ahead/behinds are more important to support than HTML and I've put a note about HTML in the UI.
* [  ] Quoutes issue

**Comment by AdamSpannbauer** [comment]
@chillywings I think I've fixed both issues.  The fixes are currently in the [`perl_12` branch](https://github.com/AdamSpannbauer/r_regex_tester_app/tree/perl_12).  I'll wait to merge/release the fixes to give you a chance to test (if you'd like).  I'll release the fixes in about a week if I don't receive any bug reports.

Thanks again for reporting the issues.

**Comment by chillywings** [comment]
Awesome, thanks @AdamSpannbauer!

**Comment by AdamSpannbauer** [comment]
PR merged.  Updated app released to: https://spannbaueradam.shinyapps.io/r_regex_tester/
