### ISSUE TITLE
multiline mode does not work

### ISSUE THREAD

**Issue by randy3k** [AdamSpannbauer/r_regex_tester_app#14]
As title. It will be great if it would support multi-line mode. 
<img width="379" alt="Screen Shot 2020-06-05 at 12 38 29 AM" src="https://user-images.githubusercontent.com/1690993/83849884-f1dfd380-a6c4-11ea-9309-4cfcf0810d7b.png">

PS: abc is underlined because of my spellchecker

**Comment by AdamSpannbauer** [comment]
Thanks for reporting.

More info: 

The issue seems related to the processing it's trying to do around backslashes. 
 Selecting/deselecting the option to escape backslashes in the test string changes the behavior, but not to the desired outcome.

<img src="https://user-images.githubusercontent.com/16326083/83863734-c2938b80-a6f1-11ea-87e5-84e3e4fec2df.png"  width="70%">

<img src="https://user-images.githubusercontent.com/16326083/83863920-0a1a1780-a6f2-11ea-90f1-b3695b7d8221.png"  width="70%">

**Comment by AdamSpannbauer** [comment]
created branch for investigating: (multiline#14)[https://github.com/AdamSpannbauer/r_regex_tester_app/tree/multiline%2314]

**Comment by AdamSpannbauer** [comment]
A potential fix has been pushed to the above-mentioned branch.  Before merging the patch, I need to do some regression testing (which should probably include writing some automated tests).

Example input/output:

* `pattern = "(?m)^ab"`
* `test_str = "abc\nabb"`
* `ignore_case = TRUE`
* `global = TRUE`
* `perl = TRUE`
* `fixed = FALSE`
* \<auto escape options\> `= FALSE`

<img src='https://user-images.githubusercontent.com/16326083/84055276-9b072200-a982-11ea-8eab-f201500cb1fe.png' width='30%'>

----

* `pattern = "^ab"`
* `test_str = "abc\nabb"`
* `ignore_case = TRUE`
* `global = TRUE`
* `perl = TRUE`
* `fixed = FALSE`
* \<auto escape options\> `= FALSE`

<img src='https://user-images.githubusercontent.com/16326083/84055318-abb79800-a982-11ea-8dcb-94e408715063.png' width='30%'>

**Comment by randy3k** [comment]
Thanks for working on it. It might make sense to make a check box for multi line mode.

**Comment by AdamSpannbauer** [comment]
Taking this issue as an excuse to do some out of scope refactoring

TODO items for closing issue:

* [x] Address initial issue
  * [added option to exclude sequences from backslash processing](https://github.com/AdamSpannbauer/r_regex_tester_app/commit/23c20b50f31fdef328244ec0b18ce7a90d2b21e8#diff-febc8045d2fd51ef92d9ac2d29140b6b)
* [x] Convert to a package to allow for testing
  * [golem-ified](https://github.com/AdamSpannbauer/r_regex_tester_app/commit/0b4cc83627e7f5ab46f6af64f83d42a8e61a2094)
* [ ] Write unit tests for regex helpers and use as regression test for current fix
* [ ] Decide on how to expose in UI
   * A checkbox for "preserve newlines in test str"?  would need a tooltip on what that means

**Comment by AdamSpannbauer** [comment]
I think I've decided to move forward with changing the default option and additional documentation.  @randy3k, if you feel this doesn't adequately address your issue, please re-open and share your thoughts.
