### ISSUE TITLE
add feature to copy R code

### ISSUE THREAD

**Issue by AdamSpannbauer** [AdamSpannbauer/r_regex_tester_app#31]
use parameters to generate example `grep` code that is copyable

**Comment by mertgoksel** [comment]
YES. YES. YES.

**Comment by AdamSpannbauer** [comment]
TODO:
* [ ] Look into syntax highlighting vs just leaving as `verbatimTextOutput()` (choose based on cost/benefit)
* [ ] Add logic to handle users including quotes in their pattern
  * current idea: 
    * if `'` in pattern -> use `"`
    * if `"` in pattern -> use `'`
    * if both in pattern -> use `"` and escape `'`
