### ISSUE TITLE
Odd output in Shiny App

### ISSUE THREAD

**Issue by aguynamedryan** [AdamSpannbauer/r_regex_tester_app#35]
I love this regex tester!  Thanks for making and sharing it.

When I was working on a file-extension stripper, I saw some odd output.  Check it out here: https://spannbaueradam.shinyapps.io/r_regex_tester/_w_f725e36c/?pattern=%5C%5C.(txt%7Cgz)&test_str=some/dumb/path.txt.gz%0Asome/dumb/path2%0Asome/dumb/path.001.txt.gz

Thanks again!

**Comment by AdamSpannbauer** [comment]
Oh and thank you for the kind words! Looking into this and I'll either make progress in [this branch](https://github.com/AdamSpannbauer/r_regex_tester_app/tree/issue%2335) or I'll report back here.

**Comment by AdamSpannbauer** [comment]
@aguynamedryan I think that your example should be functioning now in the live app.

thanks for reporting and let me know if you run into any further issues!

your test link:
https://spannbaueradam.shinyapps.io/r_regex_tester/_w_f725e36c/?pattern=%5C%5C.(txt%7Cgz)&test_str=some/dumb/path.txt.gz%0Asome/dumb/path2%0Asome/dumb/path.001.txt.gz
